run:
  go: '1.18'
  timeout: 5m
  modules-download-mode: readonly


linters-settings:
  golint:
    min-confidence: .8

linters:
  enable:
    - errcheck
    - goimports
    # - golint
    - govet
    - staticcheck
    - structcheck
    - gofmt
    - revive
    # - wsl 空格检测

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

# references:
# https://segmentfault.com/a/1190000040413280#:~:text=golangci-lint,%E6%98%AF%E4%B8%80%E4%B8%AA%E9%9B%86%E6%88%90%E5%B7%A5%E5%85%B7%EF%BC%8C%E5%AE%83%E9%9B%86%E6%88%90%E4%BA%86%E5%BE%88%E5%A4%9A%E9%9D%99%E6%80%81%E4%BB%A3%E7%A0%81%E5%88%86%E6%9E%90%E5%B7%A5%E5%85%B7%EF%BC%88%E9%9D%99%E6%80%81%E4%BB%A3%E7%A0%81%E5%88%86%E6%9E%90%E6%98%AF%E4%B8%8D%E4%BC%9A%E8%BF%90%E8%A1%8C%E4%BB%A3%E7%A0%81%E7%9A%84%EF%BC%89%EF%BC%8C%E6%88%91%E4%BB%AC%E9%80%9A%E8%BF%87%E9%85%8D%E7%BD%AE%E8%BF%99%E4%B8%AA%E5%B7%A5%E5%85%B7%EF%BC%8C%E4%BE%BF%E5%8F%AF%E7%81%B5%E6%B4%BB%E5%90%AF%E7%94%A8%E9%9C%80%E8%A6%81%E7%9A%84%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83%E6%A3%80%E6%9F%A5%E3%80%82
# https://github.com/uber-go/guide